create table users
(
    id       bigint generated by default as identity primary key,
    username varchar(100) not null unique,
    password varchar(255) not null,
    number_phone varchar(11),
    balance DOUBLE PRECISION
);

create table scooters
(
    id         bigint generated by default as identity primary key,
    model      varchar(200) not null,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    status   varchar(10) not null check (status in ('BUSY', 'FREE', 'BROKEN'))
);

create table trip
(
    id       bigint generated by default as identity primary key,
    scooter_id bigint not null,
    user_id  bigint not null,
    start_time timestamp not null,
    end_time   timestamp not null,
    start_latitude DOUBLE PRECISION,
    start_longitude DOUBLE PRECISION,
    end_latitude DOUBLE PRECISION,
    end_longitude DOUBLE PRECISION,
    price_per_minute DOUBLE PRECISION,
    constraint event_participants_event_id_fk foreign key (scooter_id) references scooters on delete cascade,
    constraint event_participants_user_id_fk foreign key (user_id) references users on delete cascade,
    constraint check_event_dates check (start_time < end_time)
);